# Numpy

* NumPy is a fundamental library for scientific computing in python
* It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures


In [1]:
# install numpy
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [1]:
# import numpy
import numpy as np

## Single dimensional  Array

In [7]:
# create a array using numpy
## Create a 1D array
npArray1 = np.array([1,2,3,4,5])

In [8]:
print(npArray1)

[1 2 3 4 5]


In [9]:
print(type(npArray1))

<class 'numpy.ndarray'>


In [10]:
# Shape of array
npArray1.shape

(5,)

## 2D Array

In [11]:
npArray2 = npArray1.reshape(1,5)
print(npArray2)


[[1 2 3 4 5]]


In [12]:
npArray3 = np.array([[1,2,3],[4,5,6]])
print(npArray3)

[[1 2 3]
 [4 5 6]]


## Create numpy in various  ways

In [15]:
npArray4 = np.arange(20,10,-1)
print(npArray4)

[20 19 18 17 16 15 14 13 12 11]


In [17]:
npArray5 = np.ones((3,4))
print(npArray5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#  identity matrix
npArray6 = np.eye(3)
print(npArray6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## NumPy array attributes

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array \n" , arr)
print("shape : " , arr.shape)
print("Number of dimensions : ", arr.ndim)
print("Number of elements : ", arr.size)
print("Data type : ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array 
 [[1 2 3]
 [4 5 6]]
shape :  (2, 3)
Number of dimensions :  2
Number of elements :  6
Data type :  int32
Item size (in bytes):  4


## NumPy Vectorized Operations

In [21]:
npArray7 = np.array([1,2 , 3, 4, 5])
npArray8 = np.array([10,15,20,25,30])

In [24]:
# Element wise addition
npAddition = npArray7 + npArray8
print(npAddition)

[11 17 23 29 35]


In [25]:
# Element wise subtraction
npSubtraction = npArray7 - npArray8
print(npSubtraction)


[ -9 -13 -17 -21 -25]


In [26]:
# Element wise multiplication 
npMultiplication = npArray7*npArray8
print(npMultiplication)

[ 10  30  60 100 150]


In [27]:
# Element wise division
npDivision = npArray7/npArray8
print(npDivision)

[0.1        0.13333333 0.15       0.16       0.16666667]


### Universal Functions

In [35]:
npArray9 = np.arange(1,100,10)

# Square root
npSqRoot = np.sqrt(npArray9)
print(npSqRoot)

[1.         3.31662479 4.58257569 5.56776436 6.40312424 7.14142843
 7.81024968 8.42614977 9.         9.53939201]


In [36]:
# Exponential
npExponen = np.exp(npArray9)
print(npExponen)

[2.71828183e+00 5.98741417e+04 1.31881573e+09 2.90488497e+13
 6.39843494e+17 1.40934908e+22 3.10429794e+26 6.83767123e+30
 1.50609731e+35 3.31740010e+39]


In [37]:
# Sine
npSine = np.sin(npArray9)
print(npSine)

[ 0.84147098 -0.99999021  0.83665564 -0.40403765 -0.15862267  0.67022918
 -0.96611777  0.95105465 -0.62988799  0.10598751]


In [39]:
# Natural log
npLog = np.log(npArray9)
print(npLog)

[0.         2.39789527 3.04452244 3.4339872  3.71357207 3.93182563
 4.11087386 4.26267988 4.39444915 4.51085951]


### Slicing and indexing

In [40]:
npArray10 = np.array([[1, 2 , 3 , 4 ], [5, 6, 7, 8], [9, 10, 11, 12]])
print(npArray10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
print(npArray10[0][1])

2


In [54]:
print(npArray10[1:,2:])

[[ 7  8]
 [11 12]]


In [55]:
npArray10[0,0] = 1000
print(npArray10)

[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


### Statistical  concepts


In [63]:
npArray11 = np.array([i**3 for i in range(5)])
mean = np.mean(npArray11)
print("mean : " , mean )

std_dev = np.std(npArray11)
print("Standard deviation : ", std_dev)

normalized_array = (npArray11 - mean)/std_dev

print(normalized_array)

print("New Mean = " , np.mean(normalized_array))

print("New Standard deviation = ", np.std(normalized_array))

mean :  20.0
Standard deviation :  24.041630560342615
[-0.83189033 -0.79029581 -0.4991342   0.29116162  1.83015873]
New Mean =  0.0
New Standard deviation =  1.0


### logical operations

In [64]:
npArray12 = np.arange(0,20,2)

print(npArray12 > 7)

[False False False False  True  True  True  True  True  True]


In [65]:
print(npArray12[npArray12 < 9])

[0 2 4 6 8]


In [75]:
print(npArray12[(npArray12 >= 5) & (npArray12 <= 9)])

[6 8]


# Pandas

* Pandas is a powerful data manipulation library in python
* It provides two primary data structures
    1. Series
        * Series is a one dimensional array like object
    2. DataFrame
        * DataFrame is a two dimensional, size mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns)


In [1]:
!pip install pandas


Defaulting to user installation because normal site-packages is not writeable


In [2]:
#import pandas
import pandas as pd

## series
* A pandas series is a one dimensional array like object that can hold any datatype
* It is similar to a column in table 


In [5]:
data = [i for i  in range(10)]
print("data \n" , data)

pd_series_data = pd.Series(data)
print("Series data \n", pd_series_data)
print(type(pd_series_data))


data 
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Series data 
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
<class 'pandas.core.series.Series'>


In [11]:
# Create a series from dictionary 

data = {'a':1, 'b':2, 'c': 3}
print("data \n: ", data)
series_dict = pd.Series(data)
print(series_dict)


data 
:  {'a': 1, 'b': 2, 'c': 3}
a    1
b    2
c    3
dtype: int64


In [12]:
data = [10,20,30]
index = ['a' , 'b', 'c']

print(pd.Series(data, index= index))

a    10
b    20
c    30
dtype: int64


## DataFrame 

In [14]:
# Create a DataFrame from a dictionary of list
data = {
    'Name' : ["Jegan", "Venujan" , "Dino"],
    'Age' : [10,15,20],
    'City': ["Badulla", "Batti" , "Vavuniya"]
}

In [15]:
print(data)

{'Name': ['Jegan', 'Venujan', 'Dino'], 'Age': [10, 15, 20], 'City': ['Badulla', 'Batti', 'Vavuniya']}


In [16]:
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Jegan   10   Badulla
1  Venujan   15     Batti
2     Dino   20  Vavuniya


In [18]:
# Create a DataFrame from list of dictionary
data = [
    {"Name":"Jegan", "Age":10 , "City":"Badulla"},
    {"Name":"Venujan", "Age":15 , "City":"Batti"},
    {"Name":"Dino", "Age":20 , "City":"Vavuniya"}
]
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Jegan   10   Badulla
1  Venujan   15     Batti
2     Dino   20  Vavuniya


In [20]:
df = pd.read_csv("./sales.csv")
df.head(5)

Index      Customer Id First Name  Last Name                   Company  \
0      1  EB54EF1154C3A78    Heather   Callahan              Mosley-David   
1      2  10dAcafEBbA5FcA   Kristina    Ferrell  Horn, Shepard and Watson   
2      3  67DAB15Ebe4BE4a     Briana   Andersen               Irwin-Oneal   
3      4  6d350C5E5eDB4EE      Patty      Ponce          Richardson Group   
4      5  5820deAdCF23EFe   Kathleen  Mccormick              Carson-Burch   

               City                   Country                Phone 1  \
0  Lake Jeffborough                    Norway           043-797-5229   
1        Aaronville                   Andorra           932-062-1802   
2       East Jordan                     Nepal             8352752061   
3  East Kristintown  Northern Mariana Islands           302.398.3833   
4       Andresmouth                     Macao  001-184-153-9683x1497   

              Phone 2                             Email Subscription Date  \
0        915.112.1727      urangel@espinoza-francis.net        2020-08-26   
1  (209)172-7124x3651           xreese@hall-donovan.com        2020-04-27   
2       (567)135-1918     haleybraun@blevins-sexton.com        2022-03-22   
3    196-189-7767x770              hohailey@anthony.com        2020-07-02   
4    552.051.2979x342  alvaradojesse@rangel-shields.com        2021-01-17   

                         Website  
0        http://www.escobar.org/  
1       https://tyler-pugh.info/  
2     https://www.mack-bell.net/  
3  https://delacruz-freeman.org/  
4            https://welch.info/

In [21]:
# Access data from DataFrame
df['First Name']

0        Heather
1       Kristina
2         Briana
3          Patty
4       Kathleen
          ...   
9995      Meghan
9996    Jeremiah
9997       Peggy
9998        Evan
9999     Melissa
Name: First Name, Length: 10000, dtype: object

In [22]:
df.loc[3]

Index                                            4
Customer Id                        6d350C5E5eDB4EE
First Name                                   Patty
Last Name                                    Ponce
Company                           Richardson Group
City                              East Kristintown
Country                   Northern Mariana Islands
Phone 1                               302.398.3833
Phone 2                           196-189-7767x770
Email                         hohailey@anthony.com
Subscription Date                       2020-07-02
Website              https://delacruz-freeman.org/
Name: 3, dtype: object

In [24]:
df.iloc[7]

Index                                          8
Customer Id                      47C5cEE243c9A7b
First Name                                 Glenn
Last Name                                Wiggins
Company                             Glenn-Harvey
City                                  Ambershire
Country              Falkland Islands (Malvinas)
Phone 1                         245-207-5608x563
Phone 2                               8806867785
Email                     changkellie@howell.com
Subscription Date                     2021-04-02
Website                      http://carlson.com/
Name: 7, dtype: object

In [25]:
df.loc[10][5]

C:\Users\User\AppData\Local\Temp\ipykernel_17212\2910919836.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[10][5]


'Lake Bobton'

In [32]:
# Accessing a specific Element
df.at[2, "First Name"]

'Briana'

In [34]:
df.iat[2,3]

'Andersen'

### Data Manipulation with DataFrame

In [ ]:
## Adding a column 
df["Random"] = [(2*i**2 - 4*i**3)/i**2 for i in range(1,10001)]
print(df)

      Index      Customer Id First Name   Last Name                   Company  \
0         1  EB54EF1154C3A78    Heather    Callahan              Mosley-David   
1         2  10dAcafEBbA5FcA   Kristina     Ferrell  Horn, Shepard and Watson   
2         3  67DAB15Ebe4BE4a     Briana    Andersen               Irwin-Oneal   
3         4  6d350C5E5eDB4EE      Patty       Ponce          Richardson Group   
4         5  5820deAdCF23EFe   Kathleen   Mccormick              Carson-Burch   
...     ...              ...        ...         ...                       ...   
9995   9996  DD0caa06ebf217c     Meghan       Cline            Richardson LLC   
9996   9997  C1C62ff90D0AfED   Jeremiah        Pena               Hodge-Nixon   
9997   9998  2EfAa6Fe435A7DA      Peggy         Key                  Vang LLC   
9998   9999  5dB06C3Fab5CCCb       Evan    Humphrey                 Gould Ltd   
9999  10000  9903e8fF4D8Ff0F    Melissa  Montgomery              Burns-Holden   

                  City     

In [42]:
# Remove column
df.drop("Random", axis= 1, inplace=True)

In [43]:
df

Index      Customer Id First Name   Last Name                   Company  \
0         1  EB54EF1154C3A78    Heather    Callahan              Mosley-David   
1         2  10dAcafEBbA5FcA   Kristina     Ferrell  Horn, Shepard and Watson   
2         3  67DAB15Ebe4BE4a     Briana    Andersen               Irwin-Oneal   
3         4  6d350C5E5eDB4EE      Patty       Ponce          Richardson Group   
4         5  5820deAdCF23EFe   Kathleen   Mccormick              Carson-Burch   
...     ...              ...        ...         ...                       ...   
9995   9996  DD0caa06ebf217c     Meghan       Cline            Richardson LLC   
9996   9997  C1C62ff90D0AfED   Jeremiah        Pena               Hodge-Nixon   
9997   9998  2EfAa6Fe435A7DA      Peggy         Key                  Vang LLC   
9998   9999  5dB06C3Fab5CCCb       Evan    Humphrey                 Gould Ltd   
9999  10000  9903e8fF4D8Ff0F    Melissa  Montgomery              Burns-Holden   

                  City                       Country                Phone 1  \
0     Lake Jeffborough                        Norway           043-797-5229   
1           Aaronville                       Andorra           932-062-1802   
2          East Jordan                         Nepal             8352752061   
3     East Kristintown      Northern Mariana Islands           302.398.3833   
4          Andresmouth                         Macao  001-184-153-9683x1497   
...                ...                           ...                    ...   
9995        Petersport                 Cote d'Ivoire   001-270-136-4738x419   
9996        Briggsport                       Namibia   +1-531-494-7645x4844   
9997    West Joyceport  United States Virgin Islands     520.109.2482x26052   
9998    Camachochester                         Niger       001-465-242-9979   
9999        Sparkstown                       Tunisia  +1-889-682-9490x65400   

                    Phone 2                                 Email  \
0              915.112.1727          urangel@espinoza-francis.net   
1        (209)172-7124x3651               xreese@hall-donovan.com   
2             (567)135-1918         haleybraun@blevins-sexton.com   
3          196-189-7767x770                  hohailey@anthony.com   
4          552.051.2979x342      alvaradojesse@rangel-shields.com   
...                     ...                                   ...   
9995   001-349-692-1755x055             nicolasandrade@bates.info   
9996  001-295-324-5502x5411                      tracy68@wade.com   
9997  +1-602-934-5901x95106    mclaughlinjulia@barnett-dorsey.com   
9998   001-639-955-2116x751  velazquezjessica@villegas-wilcox.com   
9999     423.632.2539x98740               ngallagher@martinez.com   

     Subscription Date                        Website  
0           2020-08-26        http://www.escobar.org/  
1           2020-04-27       https://tyler-pugh.info/  
2           2022-03-22     https://www.mack-bell.net/  
3           2020-07-02  https://delacruz-freeman.org/  
4           2021-01-17            https://welch.info/  
...                ...                            ...  
9995        2022-04-27       http://thomas-ramos.com/  
9996        2022-01-17      https://www.campbell.com/  
9997        2022-01-13   http://www.george-scott.com/  
9998        2020-04-14        https://www.payne.info/  
9999        2020-06-27              http://nixon.net/  

[10000 rows x 12 columns]

In [44]:
df.describe()

Index
count  10000.00000
mean    5000.50000
std     2886.89568
min        1.00000
25%     2500.75000
50%     5000.50000
75%     7500.25000
max    10000.00000

# Data manipulation with Pandas and NumPy



In [48]:
df = pd.read_csv("./data.csv")


In [49]:
df.head(10)

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [50]:
df.tail(10)

Date Category  Value   Product  Sales Region
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [51]:
df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [54]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

## Handling missing values

In [55]:
df.isnull()

Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [56]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [57]:
df.isnull().any(axis = 1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [58]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [61]:
df_filed_0 = df.fillna(0)

In [63]:
# filling missing value with mean
df['sales_fill_NA'] = df['Sales'].fillna(df['Sales'].mean())
df

Date Category  Value   Product  Sales Region  sales_fill_NA
0   2023-01-01        A   28.0  Product1  754.0   East     754.000000
1   2023-01-02        B   39.0  Product3  110.0  North     110.000000
2   2023-01-03        C   32.0  Product2  398.0   East     398.000000
3   2023-01-04        B    8.0  Product1  522.0   East     522.000000
4   2023-01-05        B   26.0  Product3  869.0  North     869.000000
5   2023-01-06        B   54.0  Product3  192.0   West     192.000000
6   2023-01-07        A   16.0  Product1  936.0   East     936.000000
7   2023-01-08        C   89.0  Product1  488.0   West     488.000000
8   2023-01-09        C   37.0  Product3  772.0   West     772.000000
9   2023-01-10        A   22.0  Product2  834.0   West     834.000000
10  2023-01-11        B    7.0  Product1  842.0  North     842.000000
11  2023-01-12        B   60.0  Product2    NaN   West     557.130435
12  2023-01-13        A   70.0  Product3  628.0  South     628.000000
13  2023-01-14        A   69.0  Product1  423.0   East     423.000000
14  2023-01-15        A   47.0  Product2  893.0   West     893.000000
15  2023-01-16        C    NaN  Product1  895.0  North     895.000000
16  2023-01-17        C   93.0  Product2  511.0  South     511.000000
17  2023-01-18        C    NaN  Product1  108.0   West     108.000000
18  2023-01-19        A   31.0  Product2  578.0   West     578.000000
19  2023-01-20        A   59.0  Product1  736.0   East     736.000000
20  2023-01-21        C   82.0  Product3  606.0  South     606.000000
21  2023-01-22        C   37.0  Product2  992.0  South     992.000000
22  2023-01-23        B   62.0  Product3  942.0  North     942.000000
23  2023-01-24        C   92.0  Product2  342.0   West     342.000000
24  2023-01-25        A   24.0  Product2  458.0   East     458.000000
25  2023-01-26        C   95.0  Product1  584.0   West     584.000000
26  2023-01-27        C   71.0  Product2  619.0  North     619.000000
27  2023-01-28        C   56.0  Product2  224.0  North     224.000000
28  2023-01-29        B    NaN  Product3  617.0  North     617.000000
29  2023-01-30        C   51.0  Product2  737.0  South     737.000000
30  2023-01-31        B   50.0  Product3  735.0   West     735.000000
31  2023-02-01        A   17.0  Product2  189.0   West     189.000000
32  2023-02-02        B   63.0  Product3  338.0  South     338.000000
33  2023-02-03        C   27.0  Product3    NaN   East     557.130435
34  2023-02-04        C   70.0  Product3  669.0   West     669.000000
35  2023-02-05        B   60.0  Product2    NaN   West     557.130435
36  2023-02-06        C   36.0  Product3  177.0   East     177.000000
37  2023-02-07        C    2.0  Product1    NaN  North     557.130435
38  2023-02-08        C   94.0  Product1  408.0  South     408.000000
39  2023-02-09        A   62.0  Product1  155.0   West     155.000000
40  2023-02-10        B   15.0  Product1  578.0   East     578.000000
41  2023-02-11        C   97.0  Product1  256.0   East     256.000000
42  2023-02-12        A   93.0  Product3  164.0   West     164.000000
43  2023-02-13        A   43.0  Product3  949.0   East     949.000000
44  2023-02-14        A   96.0  Product3  830.0   East     830.000000
45  2023-02-15        B   99.0  Product2  599.0   West     599.000000
46  2023-02-16        B    6.0  Product1  938.0  South     938.000000
47  2023-02-17        B   69.0  Product3  143.0   West     143.000000
48  2023-02-18        C   65.0  Product3  182.0  North     182.000000
49  2023-02-19        C   11.0  Product3  708.0  North     708.000000